name: 'gnome_tutorial'
version: 0.0.1
description: Gnome Tutorial
author: Sanford Redlich <siredlich@gmail.com>
environment:
  sdk: '^1.9.3'
dependencies:
  angular2: any
  browser: "^0.10.0"
dev_dependencies:
  test: any