name: 'angular2_gnome_example_app'
version: 0.0.4
description: Angular2 Dart gnome example app
author: Sanford Redlich <siredlich@gmail.com>
environment:
  sdk: '^1.9.3'
dependencies:
  angular2: "2.0.0-alpha.25"
  browser: "^0.10.0"
dev_dependencies:
  test: any