name: 'angular2_gnome_example_app'
version: 0.0.5
description: Angular2 Dart gnome example app
author: Sanford Redlich <siredlich@gmail.com>
environment:
  sdk: '1.11.0'
dependencies:
  angular2: "2.0.0-alpha.31"
  browser: "0.10.0+2"
  json_object: "1.0.19"
dev_dependencies:
  test: "0.12.3+7"

transformers:
  - angular2:
      entry_point: web/index.dart # see docs: https://github.com/angular/angular/wiki/Angular-2-Dart-Transformer
      #reflection_entry_point: web/index.dart # not needed if ReflectionCapabilities is specified in the "entry_point" file above
  - $dart2js:
      minify: true
      #commandLineOptions: [--trust-type-annotations, --trust-primitives, --dump-info]
        # trust-* tells Dart to trust your type annotations and to therefore be able to prune more JS, see: http://dovdev.com/get-the-most-out-of-dart2js-with-a-little-trust/
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
